# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_coordinates works", {
  
  both_valid_latitude <- c(40.766, 40.799)
  both_valid_longitude <- c(-73.96, -73.95)
  both_invalid_latitude <- c(30, 32)
  both_invalid_longitude <- c(-100, -99)
  one_invalid_latitude <- c(40.766, 50)
  one_invalid_longitude <- c(-73.95, -100)
  
  expect_equal(
    object = check_coordinates(
      latitude = both_valid_latitude,
      longitude = both_valid_longitude
    ),
    expected = c(TRUE, TRUE)
  )
  
  expect_equal(
    object = check_coordinates(
      latitude = both_invalid_latitude,
      longitude = both_invalid_longitude
    ),
    expected = c(FALSE, FALSE)
  )
  
})

test_that("check_coordinates dosnt works", {
  
  expect_error(
    check_coordinates(
      latitude = "20",
      longitude = "10"
    ),
    regexp = "latitude and longitude should be numeric"
  )
  
})
  
