# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_plus_in_primary_fur_color works", {
  
  expect_equal(
    object = check_plus_in_primary_fur_color(
      primary_fur_color = c("red", "yellow")
    ),
    expected = c(TRUE, TRUE)
  )
  
    
  expect_equal(
    object = check_plus_in_primary_fur_color(
      primary_fur_color = c("Black", "Cinnamon", "Black")
    ),
    expected = c(TRUE, TRUE, TRUE)
  )
  
  expect_equal(
    object = check_plus_in_primary_fur_color(
      primary_fur_color = c("Black", "Black+Cinnamon", "Black")
    ),
    expected = c(TRUE, FALSE, TRUE)
  )
  
  
})

test_that("check_plus_in_primary_fur_color doesnt work", {
  
  expect_error(
    object = check_plus_in_primary_fur_color(primary_fur_color = 2),
    regexp = "primary_fur_color doit etre de type character"
  )
})
