# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

#' Get a message with a number of rows 
#'
#' @param df Data.frame. The dataset to be used
#' 
#' @importFrom glue glue
#'
#' @return a message
#' @export
#'
#' @examples
#' get_df_nrows(df = iris)
#' get_df_nrows(df = mtcars)
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observation"))
}
